### ISSUE TITLE
[$500] API wrapper

### ISSUE THREAD

**Issue by cwdcwd** [topcoderinc/Suedstadt-api-wrapper#2]
We now have our 3 endpoints stood up [here](https://suedstadt-dev-api.herokuapp.com/).
We'd like to wrap calls to these endpoint in a Swift component so that we can then use it on our Swift app to call for data. The calls that we need to make are:

- MLI 3: Related Card Listing Inquiry
  + Pass the customer number to fetch the card information
  + Retrieve the Card number, card name, etc. (Logo description is the Card Name)
- MLI 11: Statement Dates Listing Inquiry 
  + Pass the card number to fetch the list of statement dates for the last 24 cycles
  + Retrieve the File number, Statement dates, etc.
- MLI 12: Fetch the Statement Summary
  + Pass the file number to fetch the statements summary
  + Retrieve the summary including the category, etc.

The JSON formats for the payloads to send and receive are described in [this wiki](https://github.com/topcoderinc/Suedstadt-api/wiki).

**Comment by callmekatootie** [comment]
PAID - http://www.topcoder.com/challenge-details/30062385/?type=develop&noncache=true
