### ISSUE TITLE
[$15] Magic string for baseURL

### ISSUE THREAD

**Issue by cwdcwd** [topcoderinc/Suedstadt-api-wrapper#5]
Move [this value](https://github.com/topcoderinc/Suedstadt-api-wrapper/blob/master/SuedstadtLibrary/Services/SuedstadtService.swift#L17) into either a plist value or environment variable that can be pulled in at build time

**Comment by callmekatootie** [comment]
PAID - http://www.topcoder.com/challenge-details/30062385/?type=develop&noncache=true
